language: ruby
rvm:
  - 1.9.3
services:
  - mysql
before_install:
  - gem update --system 1.8.24
  - gem --version
  - cp config/database.yml.sample config/database.yml
before_script:
  - RAILS_ENV=test bundle exec rake db:reset
script:
  - RAILS_ENV=test bundle exec rake test
