development:
  adapter: mysql2
  database: nakkikone_development
  username: nakki
  password: nakkipasswd
  pool: 5

test:
  adapter: mysql2
  database: nakkikone_test
  username: nakki
  password: nakkipasswd
  pool: 5
