development:
  adapter: mysql2
  database: nakkikone_development
  username: nakki
  password: nakki
  pool: 5

test:
  adapter: mysql2
  database: nakkikone_test
  username: nakki
  password: nakki
  pool: 5

production:
  adapter: mysql2
  database: nakkikone_production
  username: nakki
  password: nakki
  pool: 5
